### ISSUE TITLE
CIA design update

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/data_threefold_projects_friends#36]
Conscious Internet Alliance needs logo
Website needs design update - images, fonts, colors
It has to be both clear (message) and exciting (drawing people to join)
Done before 1st June

**Comment by Sacha96** [comment]
Zia and I are working on crystal twin designs - taking much time and slowing down other plans such as CIA rebranding (much needed).

I came up with a easy update to bring something simple yet powerful - https://docs.google.com/document/d/1NwYKag9P0Z_qieXxjPPUjP2BLWoYcEyPz5iA_4-nLE0/edit

Note that working CIA and Crystal at the same time will slow down the delivery for crystal - set for 1st of June. However, CIA is very important for TF growth at the moment. 

Need the green light of @despiegk to allocate resources.

**Comment by Sacha96** [comment]
@Vilnite found designer and will push changes
