### ISSUE TITLE
define which projects are circles

### ISSUE THREAD

**Issue by Hamdy** [threefoldfoundation/data_threefold_projects_friends#44]
for circles. we need to add `is_circle = true` flag  in the info section of a project

**Comment by Sacha96** [comment]
hey guys! where should I define those circles? After talking with thabet, I understand it's to related to those circles in which activities are happening, i.e. marketing, matchmakers, bisdev, etc... 
Should I take the links from TF Circle tool and bring it here itself?

**Comment by Hamdy** [comment]
I guess in this case, you might need to add new project under `info/projects `for each circle you gonna add; i.e if circle is called marketing, you going to create projects/marketing directory
with the proper markdown and everything like any other project
with the difference that you add to info section `is_circle = true` in the markdown page describing that project/circle
I think @Vilnite might help in doing so
