### ISSUE TITLE
Content for community website

### ISSUE THREAD

**Issue by Hamdy** [threefoldfoundation/data_threefold_projects_friends#45]
For the community website we agreed on the following

- Community data is coming from the existing `People` directory (we need to add extra data per person) 
- Circles data is coming from  a new directory called `circles`

**Updates to people** 
- we have new memberships ```employee, contributor, investor, coder, matchmaker, hacker, friend, threefoldteam, crystalteam ``` please add the proper memberships to each person

- in the `info` section for each person add a new field `circles = ` where it contains list of circles this person belongs to and for each circle, the role that this person plays in that circle
the roles we have are : ```[coordinator, stakeholder (affected in one way or another), member (full time), contributor (not full time), follower```
**example**:
- if a person belongs to circles `a & b` and their role in `a` is `coordinator` and in `b` role is `stakeholder` then we can have something like
```circles = [{"name": "a", "role": "coordinator"}, {"name": "b", "role": "stakeholder"}]```
- if person does not belong to any circles, then we put `circles = []`

**Circles**
- markdown content
- no `milestones`  section
- links sections will look like
```
[links]
threefold_circles_url = ""   # link on circles.threefold
threefold_forum_url = "" # link on forums
freeflow_connect_room = "" # chat room on freeflow connect
chat_page_url = "" 
video = "" if there's a video
```

- info section
```
[info]
name = "3Bot"
rank = 5
mission = ""
team = [{"name": "Kristof" , "role" : "coordinator"}, {"name": "Kristof2" , "role" : "coordinator"}, {"name", "coordinator"}] # see above for list of circles roles
countries = ["Global"]
cities = ["Global"]
```

- Echo system (new categories)
```
[ecosystem]
categories = ["tech", "threefold", "crystaltwin", "promotion", "operations", "tfgrid", "tokens", "organization", "ecosystem"]
```

**Comment by Sacha96** [comment]
adding these where?

**Comment by despiegk** [comment]
these specs are not the right ones, e.g. employee, contributor, investor, coder, matchmaker, hacker, friend, threefoldteam, crystalteam  is not correct

also not clear what the data format is
